-- create company table --
CREATE TABLE "DC_COMPANY" ("COMPANY_ID" NUMBER(7,0), "COMPANY_CODE" VARCHAR2(15), "COMPANY_NAME" VARCHAR2(255), "ADDRESS" VARCHAR2(255), "TELEPHONE" VARCHAR2(255), "FAX" VARCHAR2(255), "SWIFT" VARCHAR2(100), "CREATED_DT" DATE DEFAULT SYSDATE, "MODIFIED_DT" DATE, "STATUS" CHAR(1), "CREATED_BY" NUMBER(7,0), "MODIFIED_BY" NUMBER(7,0), "LOGO" NUMBER(7,0), "LINK_TRAVEL_TO_SYNERGY" CHAR(1), "DR_ACC_CODE" VARCHAR2(255), "CR_ACC_CODE" VARCHAR2(255), "EXCESS_CR_ACC_CODE" VARCHAR2(255), "LESS_DR_ACC_CODE" VARCHAR2(255), "FORM_CODE" VARCHAR2(255), "EQUAL_CR_ACC_CODE" VARCHAR2(255), "ADVANCE_DR_ACC_CODE" VARCHAR2(255), "ADVANCE_CR_ACC_CODE" VARCHAR2(255)) ;

-- ----------------------------------------
-- country---\
CREATE TABLE "DC_COUNTRIES" (
    "COUNTRY_ID"      NUMBER(7, 0),
    "COUNTRY_CODE"    CHAR(2),
    "COUNTRY_NAME"    VARCHAR2(150),
    "CURRENCY_CODE"   CHAR(4),
    "NORTH"           VARCHAR2(35),
    "SOUTH"           VARCHAR2(35),
    "EAST"            VARCHAR2(35),
    "WEST"            VARCHAR2(35),
    "CAPITAL"         VARCHAR2(250),
    "CONTINENT CODE"  CHAR(2),
    "CONTINENT"       VARCHAR2(100),
    "AREA"            VARCHAR2(20),
    "ISO_CODE"        CHAR(3)
);

COMMENT ON COLUMN "DC_COUNTRIES"."NORTH" IS
    'North Coordinate';

COMMENT ON COLUMN "DC_COUNTRIES"."SOUTH" IS
    'South Coordinate ';

COMMENT ON COLUMN "DC_COUNTRIES"."EAST" IS
    'East Coordinate';

COMMENT ON COLUMN "DC_COUNTRIES"."WEST" IS
    'West Coordinate';

COMMENT ON COLUMN "DC_COUNTRIES"."AREA" IS
    'Area in Sq. K.M.';

---------------------------------
-- DC_BRANCHES----------
CREATE TABLE "DC_BRANCHES" (
    "BRANCH_ID"       NUMBER(7, 0),
    "COUNTRY_ID"      NUMBER(7, 0),
    "BRANCH_CODE"     VARCHAR2(15),
    "BRANCH_NAME"     VARCHAR2(255),
    "STREET_ADDRESS"  VARCHAR2(255),
    "TELEPHONE"       VARCHAR2(255),
    "FAX"             VARCHAR2(255),
    "EMAIL"           VARCHAR2(255),
    "REMARKS"         VARCHAR2(255),
    "STATUS"          CHAR(1) DEFAULT 'E',
    "CREATED_DT"      DATE DEFAULT sysdate,
    "MODIFIED_DT"     DATE,
    "CREATED_BY"      NUMBER(7, 0),
    "MODIFIED_BY"     NUMBER(7, 0),
    "COMPANY_ID"      NUMBER(7, 0)
);

--------------------------------
-- department
CREATE TABLE "DC_DEPARTMENTS" (
    "DEPARTMENT_ID"      NUMBER(7, 0),
    "COUNTRY_ID"         NUMBER(7, 0),
    "DEPARTMENT_CODE"    VARCHAR2(15),
    "DEPARTMENT_NAME"    VARCHAR2(255),
    "REMARKS"            VARCHAR2(255),
    "PARENT_DEPARTMENT"  NUMBER(7, 0),
    "STATUS"             CHAR(1) DEFAULT 'E',
    "CREATED_DT"         DATE DEFAULT sysdate,
    "MODIFIED_DT"        DATE,
    "CREATED_BY"         NUMBER(7, 0),
    "MODIFIED_BY"        NUMBER(7, 0),
    "BRANCH_ID"          NUMBER(7, 0),
    "COMPANY_ID"         NUMBER(7, 0) DEFAULT NULL
);
-- roles
CREATE TABLE "DC_ROLES" (
    "ROLE_ID"       NUMBER(7, 0),
    "ROLE_NAME"     VARCHAR2(100),
    "REMARKS"       VARCHAR2(255),
    "STATUS"        CHAR(1) DEFAULT 'E',
    "CREATED_DT"    DATE DEFAULT sysdate,
    "MODIFIED_DT"   DATE,
    "CREATED_BY"    NUMBER(7, 0),
    "MODIFIED_BY"   NUMBER(7, 0),
    "CONTROL"       VARCHAR2(2) DEFAULT 'F',
    "ALLOW_ADD"     CHAR(1) DEFAULT 'Y',
    "ALLOW_UPDATE"  CHAR(1) DEFAULT 'Y',
    "ALLOW_DELETE"  CHAR(1) DEFAULT 'Y'
);
---menus
CREATE TABLE "DC_MENUS" (
    "MENU_CODE"         VARCHAR2(15),
    "MENU_ID"           NUMBER(7, 0),
    "MENU_NAME"         VARCHAR2(50),
    "PARENT_MENU"       NUMBER(7, 0),
    "MENU_DESCRIPTION"  VARCHAR2(200),
    "ROUTE"             VARCHAR2(50),
    "STATUS"            CHAR(1) DEFAULT NULL,
    "CREATED_DT"        DATE DEFAULT sysdate,
    "MODIFIED_DT"       DATE,
    "ICON_CLASS"        VARCHAR2(100),
    "ACTION"            VARCHAR2(50),
    "MENU_INDEX"        NUMBER(7, 0),
    "CREATED_BY"        NUMBER(7, 0),
    "MODIFIED_BY"       NUMBER(7, 0),
    "IS_VISIBLE"        CHAR(1) DEFAULT 'Y'
);

-- create role permission
  CREATE TABLE "DC_ROLE_PERMISSIONS" ("ROLE_ID" NUMBER(7,0), "MENU_ID" VARCHAR2(50), "STATUS" CHAR(1) DEFAULT 'E', "CREATED_DT" DATE DEFAULT SYSDATE, "MODIFIED_DT" DATE) ;